### ISSUE TITLE
Bspwm

### ISSUE THREAD

**Issue by arpangreat** [arcolinux/arcolinux-bspwm#2]
I have arcolinuxb-xtended install , and in bspwm i have made some tweaks as of changing the wallpaper using `feh` but the problem is , every second the wallpaper is automatically changed and i have no idea how it is happening.

FYI - I have no .xinitrc or .Xresources tweaked

 [M Dotfiles](https://www.github.com/arpangreat/dotfiles)

Pls , help

**Comment by arcolinuxz** [comment]
see discord
not the correct medium to ask questions
